name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

      - name: Trigger Frontend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}
